apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails
          # image: your image
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: rails-log
              mountPath: /home/ruby/log
            - name: tmp
              mountPath: /home/ruby/tmp
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 30000
            runAsGroup: 30000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: rails-log
          emptyDir: {}
        - name: tmp
          emptyDir: {}

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
