apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: rails
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 3000
  # loadBalancerSourceRanges:
  #   - ""

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  defaultBackend:
    service:
      name: hello-service
      port:
        number: 8080
